services:
  turso:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    container_name: ui-compare-turso
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./db/data:/var/lib/libsql
