name = "ui-compare-api"
main = "src/worker.ts"
compatibility_date = "2024-09-28"
legacy_env = false

[vars]
TURSO_DATABASE_URL = "http://127.0.0.1:8080"
TURSO_AUTH_TOKEN = ""
STACKBLITZ_WEBHOOK_SECRET = ""
FIREBASE_PROJECT_ID = ""
FIREBASE_WEB_API_KEY = ""
FIREBASE_AUTH_EMULATOR = ""
TURNSTILE_SECRET_KEY = ""

[env.production.vars]
TURSO_DATABASE_URL = "${TURSO_DATABASE_URL}"
TURSO_AUTH_TOKEN = "${TURSO_AUTH_TOKEN}"
STACKBLITZ_WEBHOOK_SECRET = "${STACKBLITZ_WEBHOOK_SECRET}"
FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
FIREBASE_WEB_API_KEY = "${FIREBASE_WEB_API_KEY}"
TURNSTILE_SECRET_KEY = "${TURNSTILE_SECRET_KEY}"
